version: "3.7"
services:
  db:
    image: mysql:5.7
    container_name: db_server
    restart: always
    env_file:
      - .env
    volumes:
      - ./db_data:/var/lib/mysql
      - ./db_data:/docker-entrypoint-initdb.d/:ro
    networks:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - VIRTUAL_HOST=phpmyadmin.domain.es
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=phpmyadmin.domain.es
      - LETSENCRYPT_EMAIL=nikip11.dev@gmail.com
      - VIRTUAL_NETWORK=proxy
    depends_on:
      - db
    restart: always
    # ports:
    #   - "8888:80"
    networks:
      - db
      - proxy

networks:
  proxy:
    external: true
  db:
    name: db
    driver: bridge