version: '3.7'
services:
  lexon_api:
    container_name: api
    build: .
    env_file:
      .env
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@db_server:3306/${DATABASE_NAME}?serverVersion=${DATABASE_VERSION}
    volumes:
      - ./src:/var/www
    networks:
      - db_net
    ports:
      - "9000:9000"
    expose:
      - 9000
    networks:
      - webserver_net
      - db

  nginx:
    container_name: webserver
    build: ./nginx
    volumes:
      - ./src:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log/nginx
    environment:
      VIRTUAL_HOST: domain.es
      VIRTUAL_PORT: 80
      VIRTUAL_NETWORK: proxy
    networks:
      - proxy
      - webserver_net

networks:
  webserver_net:
  proxy:
    external: true
  db:
    external: true